---
repos:
  #
  # format first
  #
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [markdown, yaml, json]
  #
  # utility checks
  #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        types_or: [markdown, yaml, json, toml]
      - id: trailing-whitespace
        types_or: [markdown, yaml, json, toml]
      - id: detect-private-key
  #
  # spelling
  #
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.4
  #   hooks:
  #     - id: codespell
  #       types_or: [markdown, yaml, json]
  #       stages: [manual]
  #
  # lint gh action files
  #
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.27
    hooks:
      - id: actionlint
  # #
  # # This one I only run manually as it's useful but subject to taste
  # #
  # - repo: https://github.com/amperser/proselint.git
  #   rev: 0.14.0
  #   hooks:
  #     - id: proselint
  #       types_or: [markdown, text]
  #       stages: [manual]
